export const USER_GET_DATA_SUCCESS = 'USER_GET_ALL_DATA';
export const USER_GET_DATA_REQUEST = 'USER_GET_DATA_REQUEST';
export const USER_GET_DATA_FAIL = 'USER_GET_DATA_FAIL';

export const USER_ALL_DATA_SUCCESS = 'USER_ALL_DATA_SUCCESS';
export const USER_ALL_DATA_FAIL = 'USER_ALL_DATA_FAIL';

export const USER_UPDATE_DATA_SUCCESS = 'USER_UPDATE_DATA_SUCCESS';
export const USER_UPDATE_DATA_FAIL = 'USER_UPDATE_DATA_FAIL';

